# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'take' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for take

  target 'takeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'takeUITests' do
    # Pods for testing
  end

end
